import React,{useEffect,useMemo,useState} from 'react';
import {sec1,sec2} from './data.js';

const nav=['Home','Sec 1 Topics','Sec 2 Topics','Mind Maps','Quizzes','Formula Sheet','Games','My Progress','Achievements','About'];
function Ring({value}){return <div className="ring" style={{'--p':`${value*3.6}deg`}}><div>{value}%<small>Completed</small></div></div>}
function Sidebar({active,setActive,progress}){return <aside><div className="brand"><b>SG MATH <span>PRO</span></b><small>Sec 1 & Sec 2</small></div><nav>{nav.map((n,i)=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}>{['⌂','📚','▣','🧠','🎯','▥','🎮','★','🏆','ⓘ'][i]}<span>{n}</span></button>)}</nav><div className="progressBox"><small>YOUR PROGRESS</small><Ring value={progress}/><button onClick={()=>setActive('My Progress')}>View Progress</button></div><div className="theme"><small>THEME</small><div>◐ ☀︎ ✦</div></div></aside>}
function TopicCard({topic,index,onOpen,done}){return <button className={`topic ${done?'done':''}`} onClick={onOpen}><span className="num">{index+1}</span><div className="glyph">{topic[2]}</div><b>{topic[0]}</b><small>{topic[1]}</small>{done&&<em>✓</em>}</button>}
function Modal({topic,onClose,onCorrect}){const [show,setShow]=useState(false);return <div className="modal" onClick={onClose}><div className="lesson" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="lessonGlyph">{topic[2]}</div><h2>{topic[0]}</h2><p>{topic[1]}</p><div className="concept"><h3>Concept snapshot</h3><p>Learn the definition, see a worked example, then test yourself. This demo lesson is intentionally concise and classroom-ready.</p></div><div className="challenge"><h3>Quick challenge</h3><strong>{topic[3]}</strong>{show?<div className="answer">Answer: {topic[4]}</div>:<button onClick={()=>{setShow(true);onCorrect()}}>Reveal answer + earn XP</button>}</div></div></div>}
function Home({openTopic,done}){return <main><section className="hero"><div className="formula f1">y = mx + c</div><div className="formula f2">a² + b² = c²</div><div className="formula f3">A = πr²</div><h1>SINGAPORE<br/><span>SECONDARY MATHEMATICS</span></h1><h2>SEC 1 & SEC 2 COMPLETE GUIDE</h2><p>Master concepts. Solve problems. Build confidence.</p><div className="featureRow"><div>▣ <b>Interactive Lessons</b><small>Animations & examples</small></div><div>🎯 <b>Smart Quizzes</b><small>Instant feedback</small></div><div>🧠 <b>Mind Maps</b><small>Visualise & connect</small></div><div>🏆 <b>Exam-Ready</b><small>MOE-style practice</small></div></div></section><section className="jump"><h3>QUICK JUMP 🚀</h3><div className="jumpCards"><button onClick={()=>openTopic(sec1[0])}><span>1</span><div><b>SECONDARY 1</b><small>12 Chapters • 120+ Concepts</small></div></button><button onClick={()=>openTopic(sec2[0])}><span>2</span><div><b>SECONDARY 2</b><small>13 Chapters • 150+ Concepts</small></div></button></div></section><TopicGrid title="SECONDARY 1" items={sec1} done={done} openTopic={openTopic}/><TopicGrid title="SECONDARY 2" items={sec2} done={done} openTopic={openTopic}/></main>}
function TopicGrid({title,items,done,openTopic}){return <section className="overview"><h3>{title}</h3><div className="grid">{items.map((t,i)=><TopicCard key={t[0]} topic={t} index={i} onOpen={()=>openTopic(t)} done={done.includes(t[0])}/>)}</div></section>}
function App(){const [active,setActive]=useState('Home');const [modal,setModal]=useState(null);const [xp,setXp]=useState(()=>+localStorage.getItem('xp')||1250);const [done,setDone]=useState(()=>JSON.parse(localStorage.getItem('done')||'[]'));
useEffect(()=>{localStorage.setItem('xp',xp);localStorage.setItem('done',JSON.stringify(done))},[xp,done]);const progress=Math.round(done.length/(sec1.length+sec2.length)*100);function complete(){if(!done.includes(modal[0])){setDone([...done,modal[0]]);setXp(xp+25)}}
const content=useMemo(()=>{if(active==='Home')return <Home openTopic={setModal} done={done}/>;if(active==='Sec 1 Topics')return <main><TopicGrid title="SECONDARY 1 TOPICS" items={sec1} done={done} openTopic={setModal}/></main>;if(active==='Sec 2 Topics')return <main><TopicGrid title="SECONDARY 2 TOPICS" items={sec2} done={done} openTopic={setModal}/></main>;return <main className="placeholder"><div><span>{active==='Quizzes'?'🎯':active==='Mind Maps'?'🧠':active==='Games'?'🎮':'✦'}</span><h1>{active}</h1><p>This module is wired into the interface and ready for the next content expansion.</p><button onClick={()=>setActive('Home')}>Back to dashboard</button></div></main>},[active,done]);
return <div className="app"><Sidebar active={active} setActive={setActive} progress={progress}/><div className="shell"><header><input placeholder="Search anything (e.g. algebra, area, quadratic)..." onKeyDown={e=>{if(e.key==='Enter'){const all=[...sec1,...sec2];const found=all.find(t=>t.join(' ').toLowerCase().includes(e.target.value.toLowerCase()));if(found)setModal(found)}}}/><div className="stats"><b>⭐ {xp} XP</b><b>👑 Level {Math.floor(xp/250)}</b><b>👤</b></div></header>{content}<footer>© 2026 SG Math Pro • Built for Singapore Students • Master Today, Excel Tomorrow! 🚀</footer></div>{modal&&<Modal topic={modal} onClose={()=>setModal(null)} onCorrect={complete}/>}</div>}
export default App;
